### ISSUE TITLE
启动脚本错误提示不友好

### ISSUE THREAD

**Issue by FuZhenn** [MapTalks/maptalks#3]
1. jre不存在时, 打开的窗口都一闪而过, 没有错误提示

2. jre正常, 但没有license时, 打开的窗口同样一闪而过, 没有错误提示

**Comment by wsw0108** [comment]
这种情况我现在解决不了。
原因在于，要连续启动多个java进程，所以只能在bat里使用start命令。
而我没有看到start命令有类似出错了保留cmd窗口或类似的选项。

**Comment by FuZhenn** [comment]
要不学习apache, 写个环境测试脚本, 在这个脚本里测试并报错

**Comment by FuZhenn** [comment]
duplicate of #11
