### ISSUE TITLE
空间查询条件不指定时，nullpointer异常产生

### ISSUE THREAD

**Issue by wsw0108** [MapTalks/maptalks#5]
https://github.com/MapTalks/maptalks/blob/master/engine-common-dao/src/java/org/maptalks/gis/dao/service/sql/SQLLayerService.java#L440

https://github.com/MapTalks/maptalks/blob/master/engine-common-dao/src/java/org/maptalks/gis/dao/service/sql/SQLLayerService.java#L451

**Comment by FuZhenn** [comment]
ILayerService里有两个方法queryJson和querySpatial, 如果有spatialFilter则调用querySpatial, 没有的话则调用queryJson

会这么分是因为queryJson用流的方式来处理数据, 不用返回List<Feature>, 性能更好一些.

这个api设计确实不是很好, 把两个方法统一起来做一下改进

**Comment by wsw0108** [comment]
will fix when #10 fixed
